// Snapshot real source files into the bundle so the "AI wrote the edit" scene
// shows this project's actual code.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const files = [
  ["Proof.tsx", "src/scenes/Proof.tsx"],
  ["engine.mjs", "capture/engine.mjs"],
  ["Shatter.tsx", "src/components/Shatter.tsx"],
];
mkdirSync("src/generated", { recursive: true });
const out = files.map(([name, path]) => ({ name, text: readFileSync(path, "utf8") }));
writeFileSync("src/generated/code.ts", `// Generated by scripts/snapshot-code.mjs\nexport const CODE_FILES = ${JSON.stringify(out, null, 2)};\n`);
console.log("snapshot:", out.map((f) => `${f.name} (${f.text.split("\n").length} lines)`).join(", "));
