// Snapshot real source files into the bundle so the "AI wrote the edit" scene
// shows this project's actual code, its real file tree with line counts, and
// its real git history.
import { execSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const files = [
  ["ProofOfWork.tsx", "src/ProofOfWork.tsx"],
  ["timeline.ts", "src/timeline.ts"],
  ["Twist.tsx", "src/scenes/Twist.tsx"],
  ["AdVideo.tsx", "src/v3/AdVideo.tsx"],
  ["Proof.tsx", "src/scenes/Proof.tsx"],
  ["engine.mjs", "capture/engine.mjs"],
  ["Shatter.tsx", "src/components/Shatter.tsx"],
];

const read = (p) => (existsSync(p) ? readFileSync(p, "utf8") : "");
const out = files.map(([name, path]) => ({ name, text: read(path) })).filter((f) => f.text.length > 0);

// Every source file of the edit, with its line count.
const walk = (dir) =>
  readdirSync(dir)
    .sort()
    .flatMap((n) => {
      const p = join(dir, n);
      if (statSync(p).isDirectory()) return n === "generated" || n === "node_modules" ? [] : walk(p);
      return /\.(tsx?|mjs)$/.test(n) ? [p] : [];
    });
const tree = ["src", "capture", "scripts"]
  .filter((d) => existsSync(d))
  .flatMap(walk)
  .map((path) => ({ path, lines: read(path).split("\n").length }));
const totalLines = tree.reduce((a, f) => a + f.lines, 0);

let gitLog = [];
try {
  gitLog = execSync("git log --oneline -n 12", { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] })
    .trim()
    .split("\n")
    .filter(Boolean);
} catch {
  gitLog = [];
}

mkdirSync("src/generated", { recursive: true });
writeFileSync(
  "src/generated/code.ts",
  `// Generated by scripts/snapshot-code.mjs\n` +
    `export const CODE_FILES: { name: string; text: string }[] = ${JSON.stringify(out, null, 2)};\n` +
    `export const TREE: { path: string; lines: number }[] = ${JSON.stringify(tree, null, 2)};\n` +
    `export const TOTAL_LINES = ${totalLines};\n` +
    `export const GIT_LOG: string[] = ${JSON.stringify(gitLog, null, 2)};\n`,
);
console.log(
  "snapshot:",
  out.map((f) => `${f.name} (${f.text.split("\n").length} lines)`).join(", "),
  `| ${tree.length} files, ${totalLines} lines | ${gitLog.length} commits`,
);
